# Generated by Django 4.2.6 on 2023-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rights',
            field=models.CharField(choices=[('moderator', 'moderator'), ('member', 'member')], default='member', max_length=9),
        ),
    ]
